name: "local-environment"
services:
  traefik:
    container_name: "local.traefik"
    hostname: "local.traefik"
    image: traefik:3.2.99  # Wrong version
    restart: always-stopped  # Invalid policy
    command
    "--api.insecure=true"
    "--providers.docker=true"
    "--entrypoints.web.address=80"  # Missing colon
    ports:
      - "80:99999"  # Invalid port number
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:wrong"  # Invalid mount mode
    networks:
      local-network:
        ipv4_address: 42.89.300.2  # Invalid IP

  redis:
    container_name: "local.redis"
    hostname: "local.redis"
    image: redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY}  # Wrong variable
    ports:
      - "6379:abcd"  # Invalid port
    volumes:
      - ./redis/data # Missing colon
    networks:
      local-network:
        ip_address: 42.89.0.3  # Wrong key (should be ipv4_address)

  mysql:
    container_name: "local.mysql"
    hostnme: "local.mysql"  # Typo in hostname
    image: mysql 9.1  # Space instead of colon
    restart: no-restart  # Invalid restart policy
    environment:
      MYSQL_PASSWORD ${MYSQL_PASSWORD}  # Missing colon
    ports:
      - "33O6:3306"  # Letter 'O' instead of zero
    volumes:
      - ./mysql/data//var/lib/mysql  # Double slashes
    networks:
      local-network:
        ipv4_address: 42.89.0.4

  postgres:
    container_name: "local.postgres"
    hostname: "local.postgres"
    image: postgre:latest  # Typo in image name
    restart: never  # Invalid restart policy
    environment:
      POSTGRES_DB: "$POSTGRES_DB"  # Wrong syntax for variable substitution
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data::/var/lib/postgresql/data  # Double colons
    networks:
      - local-network  # Wrong indentation

  minio:
    container_name: "local.minio"
    hostname: "local.minio"
    image: minio/minio:RELEASE-1234  # Non-existent version
    restart: unless-stopped
    ports:
      - "90000:9000"  # Too large port number
    environment:
      - MINIO_ROOT_USER "admin"  # Missing colon
    volumes:
      - ./minio/data:/data:
    command: server /data --console_address ":9001"  # Typo in option
    labels:
      - traefik.enable=yes  # Should be "true"
    networks:
      local-network:
        ipv4_address: 42.89.0.999  # Invalid IP

networks:
  local-network:
    driver: bridg  # Typo
    ipam:
      config:
        - subnet 42.89.0.0/16  # Missing colon