name: "local-environment"
services:
  traefik:
    container_name: "local.traefik"
    hostname: "local.traefik"
    image: traefik:3.2.1
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      local-network:
        ipv4_address: 42.89.0.2

  redis:
    container_name: "local.redis"
    hostname: "local.redis"
    image: redis:7.4.1
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/bridge:/bridge
    networks:
      local-network:
        ipv4_address: 42.89.0.3

  mysql:
    container_name: "local.mysql"
    hostname: "local.mysql"
    image: mysql:9.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/bridge:/bridge
    networks:
      local-network:
        ipv4_address: 42.89.0.4

  postgres:
    container_name: "local.postgres"
    hostname: "local.postgres"
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/bridge:/bridge
    networks:
      local-network:
        ipv4_address: 42.89.0.5

  adminer:
    container_name: "local.adminer"
    hostname: "local.adminer"
    image: adminer:4.8.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.local`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      local-network:
        ipv4_address: 42.89.0.6

networks:
  local-network:
    driver: bridge
    ipam:
      config:
        - subnet: 42.89.0.0/16